version: '2.17.3'
services:
  backend:
    image: backend-test
    restart: always
    ports:
      - '80:80'
  frontend:
    image: frontend-changed
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend